version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env.develop

  redis:
    image: redis:7
    container_name: redis

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.develop
    container_name: social_network_api
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
