services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis

  api:
    image: social_network_api
    container_name: social_network_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["sh", "docker/app.sh"]
    ports:
      - 8000:8000
