services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis

  api:
    image: social_network_api:latest
    container_name: social_network_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
