"""Added a profile photo

Revision ID: dd42d543649b
Revises: 9cde8e5c2f1d
Create Date: 2024-11-10 16:14:45.337390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd42d543649b'
down_revision: Union[str, None] = '9cde8e5c2f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_column('profile', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'photo_url')
    # ### end Alembic commands ###
